// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_WC-DHgw_AciAncntgvIj2DpQ-SnMAR4',
    appId: '1:609694414648:web:24bf6617189e1684bf73cd',
    messagingSenderId: '609694414648',
    projectId: 'chat-app-8f377',
    authDomain: 'chat-app-8f377.firebaseapp.com',
    storageBucket: 'chat-app-8f377.appspot.com',
    measurementId: 'G-8CTNWSQXT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgpiraff69F8F8ySgEu-CABcw32tY5nvw',
    appId: '1:609694414648:android:83d3774c766018cabf73cd',
    messagingSenderId: '609694414648',
    projectId: 'chat-app-8f377',
    storageBucket: 'chat-app-8f377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZAndXdDabe7_ae2weQcdpWgTeA4i1BFk',
    appId: '1:609694414648:ios:4fe256bbc93072c5bf73cd',
    messagingSenderId: '609694414648',
    projectId: 'chat-app-8f377',
    storageBucket: 'chat-app-8f377.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZAndXdDabe7_ae2weQcdpWgTeA4i1BFk',
    appId: '1:609694414648:ios:4fe256bbc93072c5bf73cd',
    messagingSenderId: '609694414648',
    projectId: 'chat-app-8f377',
    storageBucket: 'chat-app-8f377.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
